name: matvis-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - jupyterlab
  - astropy
  - matplotlib
  - numpy
  - psutil
  - pyuvdata
  - pyyaml
  - setuptools_scm
  - astropy-healpix
  - mpi4py
  - python-casacore
  - pytest
  - jupyter-resource-usage
  - bokeh
  - jupyter_bokeh
  - h5py
