time_interval: 120
time_interval_unit: "seconds"
antenna_positions_file: "../data/antenna.txt"
output_file: "complex_visibility.h5"
plot_skymodel_every_hour: true
use_gleam: true
save_simulation_data: true
gleam_flux_limit: 60