time_interval: 60
time_interval_unit: "seconds"
antenna_positions_file: "../data/antenna.txt"
output_file: "complex_visibility.h5"
plot_skymodel_every_hour: true
use_gleam: true
gleam_flux_limit: 50
save_simulation_data: true
total_duration_unit: "days"
total_duration: 1
start_frequency: 76.0
frequency_interval: 1000000
total_frequency_bandwidth: 400
frequency_unit: "MHz"
start_time: "2025-01-01T00:00:00"